// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmsmljkeedqfrbgsqipf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tc21samtlZWRxZnJiZ3NxaXBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2Mzg4OTAsImV4cCI6MjA3MDIxNDg5MH0.VFc1vLtZgRBlbWa6UA2DTvdag-0sSKVfxpqIQJKwLlg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});